name: Deploy to Pages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <staging|prod>"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Build
        run: docker build --output type=local,dest=dist .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
      - name: Deploy to Pages
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=clangensim --branch=${{ github.event.inputs.environment }}
